### PR TITLE
Fix(common): format logs in correct local timezone

### LINKED ISSUE #834: [Bug]: `shuttle deploy` incorrectly reports times as "Zulu"
### What happened?

```
> cargo shuttle deploy --allow-dirty

2023-05-01T12:21:31.543482956Z  INFO Entering queued state
[...]
```

I'm in the EDT timezone. So that should be `2023-05-01T16:21:31.543482956Z` or just `2023-05-01T12:21:31.543482956`.

A `Z` on the end of a timestamp indicates "Zulu" time which is the military name for UTC.

### Version

0.15.0

### Which operating systems are you seeing the problem on?

Windows

### Which CPU architectures are you seeing the problem on?

_No response_

### Relevant log output

```sh
> cargo shuttle deploy --allow-dirty

2023-05-01T12:21:31.543482956Z  INFO Entering queued state
2023-05-01T12:21:31.543503663Z TRACE shuttle_deployer::deployment::queue: getting a build slot
2023-05-01T12:21:31.548494787Z TRACE {uri="http://gateway:8001/stats/load"} shuttle_deployer::deployment::gateway_client: calling gateway
2023-05-01T12:21:31.550793860Z DEBUG hyper::client::connect::http: connecting to 10.99.82.119:8001
2023-05-01T12:21:31.553419377Z DEBUG hyper::client::connect::http: connected to 10.99.82.119:8001
2023-05-01T12:21:31.555555361Z DEBUG hyper::client::pool: pooling idle connection for ("http", gateway:8001)
[...]
```

### Duplicate declaration

- [X] I have searched the issues and there are none like this.

### LINKED ISSUE #843: [Feature]: Improve errors for panics in the main function
### Describe the feature

Currently a few panics in the main function will return a log error of no panic message, which is the default if no panic message is received in the alpha runtime: https://github.com/shuttle-hq/shuttle/blob/main/runtime/src/alpha/mod.rs#L330

Requirements
- Reproduce this on a local environment
- Investigate why it is happening
- Propose a solution to fix it

### Suggestion or Example of how the feature would be used

_No response_

### Duplicate declaration

- [x] I have searched the issues and this feature has not been requested before.

### PR DESCRIPTION
**Pull request by timonv**
## Description of change
Logs were formatted in UTC regardless of local timezone, resulting in incorrect times. We now format the datetime with rfc3339 which includes the correct timezone.

Testing is a bit hacky with the mutex, as per the comment, Time uses libc to get the timezone. By forcing the env var to the expected timezone we get the result we want. Originally had more than one test, hence the mutex. Decided to leave it in, as any additional test using timezones would yield crazy racing errors. Happy to remove it if needed.

Closes #834 

## How has this been tested? (if applicable)
Added unit tests.
Having some issues running the full test suite / local env. Should be alright but timezones.

### CODE REVIEW

File: common/src/lib.rs [hunk 1]
```diff
@@ -1,3 +1,7 @@
+#[cfg(test)]
+#[cfg(macro_use)]
+extern crate lazy_static;
+
```
Comment (chesedo) [inline common/src/lib.rs:4]: This might not be needed since the test is including (`use`ing) it too. It's also a bit unexpected

File: common/src/log.rs [hunk 2]
```diff
@@ -121,3 +121,54 @@ impl From<&tracing::Level> for Level {
...
     }
 }
+
+#[cfg(test)]
+mod tests {
+    use super::*;
+    use lazy_static::lazy_static;
+
+    lazy_static! {
+        static ref TZ_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());
```
Comment (chesedo) [inline common/src/log.rs:131]: Can we rather use `once_cell`?

Comment (chesedo) [reply common/src/log.rs:131]: Well, maybe removing it will be better since there is only one test now :smile:

**Review by chesedo — COMMENTED** [review]
Nice, thanks @timonv! :partying_face: 

I left some cleanup related comments

**Comment by timonv** [comment]
Thanks for the feedback, added a clarifying comment, cleaned up and readded dim()

**Comment by timonv** [comment]
> Having some issues running the full test suite / local env. Should be alright but timezones.

image

**Review by oddgrd — APPROVED** [review]
This looks great, thanks Timon! Thanks for the test, the screenshot and the thorough PR description as well :heart_eyes:
